### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку vsd Сташевский Леонид

### ISSUE THREAD

**Issue by e5l** [e5l/au-linux-kernel-spring-2016#2]
Сделал фикс и rebase. Появился новый коммит, родитель которого два ребёнка(но диф не отображается).
https://github.com/e5l/au-linux-kernel-spring-2016/commit/e9b9f772bac120d91e09c85c840420be97df1469

На всякий случай два исходных коммита:
https://github.com/e5l/au-linux-kernel-spring-2016/commit/ecd543292f260caf9a592fbf9d23c7786f9a990e
https://github.com/e5l/au-linux-kernel-spring-2016/commit/400b11b797fab332603df913eda5293321721f76

**Comment by eabatalov** [comment]
Good. 100% for the task.
